### ISSUE TITLE
TypeError: "file" argument must be a non-empty string on AArch64

### ISSUE THREAD

**Issue by vanloswang** [oVirt/ovirt-web-ui#338]
The version of ovirt-web-ui is 1.1.0, the version of ovirt-engine-yarn is 0.24.4-1 and the version of ovirt-engine-nodejs is 8.0.0. All of them is come from oVirt 4.1 repo. Build it on CentOS 7 aarch64 and  failed with following message:
```bash
$ node scripts/build.js 
Building with homepagePath: /ovirt-engine/web-ui/
Creating an optimized production build...
child_process.js:360
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:360:11)
    at spawnSync (child_process.js:487:38)
    at Compiler.checkFlowStatus (/root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/node_modules/flow-babel-webpack-plugin/index.js:72:13)
    at Compiler.applyPluginsAsync (/root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.run (/root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/node_modules/webpack/lib/Compiler.js:167:7)
    at build (/root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/scripts/build.js:101:19)
    at recursive (/root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/scripts/build.js:61:3)
    at /root/rpmbuild/BUILD/ovirt-web-ui-1.1.0/node_modules/recursive-readdir/index.js:31:14
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [ovirt-web-ui] Error 1
```

**Comment by mareklibra** [comment]
Might be related: https://github.com/react-native-training/create-xp-app/issues/18

**Comment by jniederm** [comment]
A guess: The error was raised in `flow-babel-webpack-plugin` while spawning a new process. This is most probably a `flow` type-checker process from package [flow-bin][1]. This package contains three platform dependent executables (see [flow-bin `package.json][2]). Non of which probably supports AArch64. That would actually make our build process platform dependent.

@vanloswang could you please retry the compilation with following [line][3] commented to disable flow-babel-webpack-plugin?

[1]: https://www.npmjs.com/package/flow-bin
[2]: https://github.com/flowtype/flow-bin/blob/v0.54.1/package.json#L22
[3]: https://github.com/oVirt/ovirt-web-ui/blob/ovirt-web-ui-1.1.0/config/webpack.config.prod.js#L245

**Comment by vanloswang** [comment]
@jniederm  compile  failed on another place after commented the code on the line. v1.2.1 provides noarch rpm, I will use the noarch package built from x86_64 util it can be compile on AArch64.
